name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install pipenv
        run: pip install pipenv
             pipenv install
      - name: Run tests
        run: |
          pipenv install pylint
          pipenv run pylint
